line-length = 120

[lint]
## E4, E7, E9 and F are the default configuration of ruff, "I" is added to handle imports
select = ["E4", "E7", "E9", "F", "I"]

[lint.isort]
## Use a single line between direct import and from import.
lines-between-types = 1
section-order = [
    "testing",
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[lint.isort.sections]
testing = ["pytest*", "*mock*"]
