# Copyright (c) 2024, RTE (https://www.rte-france.com)
#
# See AUTHORS.txt
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of the Antares project.
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional

import pandas as pd

from antares.craft.exceptions.exceptions import OutputDataRetrievalError
from antares.craft.service.base_services import BaseOutputService


class MCIndAreasDataType(Enum):
    """Types of files generated by the simulation for each area, for each year.

    Attributes:
        VALUES: General values of variables (price, load, generation, etc.).
            Files of this type have the same size for all areas.
            In the UI, it corresponds to displaying **General values**.
        DETAILS: Values regarding dispatchable thermal generating plants.
            File sizes differ by area.
            In the UI, it corresponds to displaying **Thermal plants**.
        DETAILS_ST_STORAGE: Values regarding the different short-term storages of each area.
            The sizes of these files differ from one area to another.
            In the UI, it corresponds to displaying **ST storages**.
        DETAILS_RES: Values regarding the different renewable clusters of each area.
            The sizes of these files differ from one area to another.
            In the UI, it corresponds to displaying **Ren. clusters**.
    """

    VALUES = "values"
    DETAILS = "details"
    DETAILS_ST_STORAGE = "details-STstorage"
    DETAILS_RES = "details-res"


class MCAllAreasDataType(Enum):
    """Types of files generated by the simulation for each area,
    containing synthetic results over all years.

    Attributes:
        VALUES: General values of variables (price, load, generation, etc.).
            Files of this type have the same size for all areas.
            In the UI, it corresponds to displaying **General values**.
        DETAILS: Values regarding dispatchable thermal generating plants.
            File sizes differ by area.
            In the UI, it corresponds to displaying **Thermal plants**.
        DETAILS_ST_STORAGE: Values regarding the different short-term storages of each area.
            The sizes of these files differ from one area to another.
            In the UI, it corresponds to displaying **ST storages**.
        DETAILS_RES: Values regarding the different renewable clusters of each area.
            The sizes of these files differ from one area to another.
            In the UI, it corresponds to displaying **Ren. clusters**.
        ID: Identifier (number) of the Monte-Carlo years for which were observed the extreme
            values of the different variables presented in the `values` files.
            In the UI, it corresponds to displaying **RecordYear**.
    """

    VALUES = "values"
    DETAILS = "details"
    DETAILS_ST_STORAGE = "details-STstorage"
    DETAILS_RES = "details-res"
    ID = "id"


class MCIndLinksDataType(Enum):
    """Types of files generated by the simulation for each link, for each year.

    Attributes:
        VALUES: values of different variables (flow, congestion rent) the list of which is common to all interconnections.
            The files of type `values` have therefore the same size everywhere.
            In the UI, it corresponds to displaying **General values**.
    """

    VALUES = "values"


class MCAllLinksDataType(Enum):
    """Types of files generated by the simulation for each area,
    containing synthetic results over all years.

    Attributes:
        VALUES: values of different variables (flow, congestion rent) the list of which is common to all interconnections.
            The files of type `values` have therefore the same size everywhere.
            In the UI, it corresponds to displaying **General values**.
        ID: Identifier (number) of the Monte-Carlo years for which were observed the extreme values
            of the different variables presented in the `values` files.
            In the UI, it corresponds to displaying **RecordYear**.
    """

    VALUES = "values"
    ID = "id"


class Frequency(Enum):
    """Time span over which the results are assessed:
    hourly detail, daily bundle, weekly bundle, monthly bundle, annual bundle.

    Attributes:
        HOURLY:
        DAILY:
        WEEKLY:
        MONTHLY:
        ANNUAL:
    """

    HOURLY = "hourly"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    ANNUAL = "annual"


@dataclass(frozen=True)
class XpansionOutputAntares:
    """Output of Xpansion investment module.

    Attributes:
        version: The version of the module used in the simulation.
    """

    version: str


@dataclass(frozen=True)
class XpansionOutputOptions:
    """Options of Xpansion output.

    Attributes:
        log_level: Solver's log severity in {0, 1, 2}.
        master_name: Name of the master problem file (automatically generated).
        problem_format:
            - MPS: Problems in MPS text format.
            - OPTIMIZED: Problems in binary SVF format.
        solver_name: Solver used for the resolution of the optimization problem.
    """

    log_level: int
    master_name: str
    problem_format: str
    solver_name: str


@dataclass(frozen=True)
class XpansionOutputIteration:
    r"""Xpansion output for a given iteration.

    Attributes:
        best_ub: Best upper bound on the optimal cost.
        cumulative_number_of_subproblem_resolutions: Cumulative number of subproblems solved from the beginning of the Benders algorithm.
        investment_cost: Investment cost of the solution at the current iteration.
        lb: Lower bound on the optimal cost: this is the solution of the master problem as it is a relaxation of the investment problem.
        master_duration: Duration of the master problem resolution.
        operational_cost: Expectation of the yearly operational cost over all MC years of the linear relaxation of an Antares simulation for the system with the current iteration investment level.
        optimality_gap: Absolute gap between the lb and the best_ub (`(best_ub - lb)`).
        overall_cost: Sum of `investment cost` and `operational_cost`.
        relative_gap: At each iteration, the algorithm computes upper and lower bounds on the optimal cost.
            The algorithm stops as soon as the quantity `(best_ub - lb) / max(|best_ub|, |lb|)`
            falls below relative_gap. For a relative gap $\alpha$, the cost of the solution returned by the algorithm satisfies:
            $$\frac{{\scriptstyle\texttt{xpansion solution cost}} - {\scriptstyle\texttt{optimal cost}}}{{\scriptstyle\texttt{optimal cost}}} < \alpha$$.
        subproblem_duration: Wall time for the resolution of all weekly Antares subproblems at the current iteration.
        ub: Overall cost of the solution of the current iteration. This may be greater than `best_ub` if a previous iteration led to a better solution.
    """

    best_ub: float
    cumulative_number_of_subproblem_resolutions: int
    investment_cost: float
    lb: float
    master_duration: float
    operational_cost: float
    optimality_gap: float
    overall_cost: float
    relative_gap: float
    subproblem_duration: float
    ub: float


@dataclass(frozen=True)
class XpansionOutputSolution:
    r"""Xpansion output solution.

    Attributes:
        investment_cost: Optimal investment cost found by the algorithm.
        iteration: Corresponding iteration for the best solution.
        operational_cost: Expectation of the yearly operational cost over all MC years of the linear relaxation of an Antares simulation for the system with the best investment.
        optimality_gap: Absolute gap between the lb and the best_ub (`(best_ub - lb)`).
        overall_cost: Sum of investment cost and `operational_cost`.
        problem_status: Problem status.
        relative_gap: At each iteration, the algorithm computes upper and lower bounds on the optimal cost.
            The algorithm stops as soon as the quantity `(best_ub - lb) / max(|best_ub|, |lb|)`
            falls below relative_gap. For a relative gap $\alpha$, the cost of the solution returned by the algorithm satisfies:
            $$\frac{{\scriptstyle\texttt{xpansion solution cost}} - {\scriptstyle\texttt{optimal cost}}}{{\scriptstyle\texttt{optimal cost}}} < \alpha$$.
        stopping_criterion: Stopping criterion for the optimization problem.
    """

    investment_cost: float
    iteration: int
    operational_cost: float
    optimality_gap: float
    overall_cost: float
    problem_status: str
    relative_gap: float
    stopping_criterion: str


@dataclass(frozen=True)
class XpansionOutputCandidateInvest:
    """Xpansion output candidate investment.

    Attributes:
        invest: Amount of investment for a given candidate.
    """

    invest: float


@dataclass(frozen=True)
class XpansionOutputCandidate:
    """Xpansion output candidate.

    Attributes:
        solution: Invested capacity at the end of the algorithm.
        max: Maximum possible investment (in MW).
        min: Minimum possible investment (in MW).
        iterations: List of the output candidate investment for each iteration.
    """

    solution: float
    max: float
    min: float
    iterations: list[XpansionOutputCandidateInvest]


@dataclass(frozen=True)
class XpansionResult:
    """Xpansion results.

    Attributes:
        antares: Antares version information.
        antares_xpansion: Antares-Xpansion version information.
        begin: Timestamp of the start of the problem resolution.
        end: Timestamp of the end of the problem resolution.
        iterations: Dictionary of all Benders iteration outputs.
        nb_weeks: Number of subproblems (= number of MC years × number of weeks solved per year).
        options: Options for Xpansion module.
        run_duration: Duration of the problem resolution.
        solution: Final optimal solution.
        candidates: Dictionary of all candidates.
    """

    antares: XpansionOutputAntares
    antares_xpansion: XpansionOutputAntares
    begin: datetime
    end: datetime
    iterations: dict[int, XpansionOutputIteration]
    nb_weeks: int
    options: XpansionOutputOptions
    run_duration: float
    solution: XpansionOutputSolution
    candidates: dict[str, XpansionOutputCandidate]


@dataclass(frozen=True)
class XpansionOutputCandidateSensitivity:
    """Xpansion output candidate sensitivity study.

    Attributes:
        lb: Minimum possible invested capacity.
        ub: Maximum possible invested capacity.
        solution_max: Maximum invested capacity in a near-optimal solution.
        solution_min: Minimum invested capacity in a near-optimal solution.
    """

    lb: float
    ub: float
    solution_max: XpansionOutputCandidateInvest
    solution_min: XpansionOutputCandidateInvest


@dataclass(frozen=True)
class XpansionOutputSensitivitySolution:
    """Xpansion output sensitivity solution.

    Attributes:
        objective: Objective value of the solution of the sensitivity analysis.
        problem_type:
            - "capex": Find a near-optimal solution with min or max capex.
            - "investment <asset name>": Find a near-optimal solution that minimizes or maximizes the investment for a given asset.
        status: Problem status.
        system_cost: System cost with the solution of the sensitivity analysis.
    """

    objective: float
    problem_type: str
    status: int
    system_cost: float


@dataclass(frozen=True)
class XpansionSensitivityResult:
    """Xpansion sensitivity results.

    Attributes:
        antares: Antares version information.
        antares_xpansion: Antares-Xpansion version information.
        best_benders_cost: Optimal objective value of the investment problem before the sensitivity analysis.
        epsilon: Allowed gap with `best_benders_cost` to consider that a solution is near-optimal (i.e. will be considered in the sensitivity analysis).
        candidates: Dictionary of candidate solutions for the sensitivity analysis.
        solution_max: Solution of the sensitivity analysis that maximises the objective.
        solution_min: Solution of the sensitivity analysis that minimises the objective.
    """

    antares: XpansionOutputAntares
    antares_xpansion: XpansionOutputAntares
    best_benders_cost: float
    epsilon: float
    candidates: dict[str, XpansionOutputCandidateSensitivity]
    solution_max: XpansionOutputSensitivitySolution
    solution_min: XpansionOutputSensitivitySolution


@dataclass
class AggregationEntry:
    """Represent an entry for aggregation queries.

    Internal class.

    Attributes:
        data_type: Whether it's `All` / `Ind` and `Area` / `Link`.
        frequency: "hourly", "daily", "weekly", "monthly", "annual".
        mc_years: Monte Carlo years to include in the query. If left empty, all years are included.
        type_ids: which links/areas to be selected (ex: "be - fr"). If empty, all are selected.
        columns_names: names or regexes (if data_type is of type details) to select columns.
    """

    data_type: MCAllAreasDataType | MCIndAreasDataType | MCAllLinksDataType | MCIndLinksDataType
    frequency: Frequency
    mc_years: Optional[list[int]] = None
    type_ids: Optional[list[str]] = None
    columns_names: Optional[list[str]] = None


class Output:
    """Output of an Antares simulation with/without Xpansion."""

    def __init__(self, name: str, archived: bool, output_service: BaseOutputService):
        self._name = name
        self._archived = archived
        self._output_service: BaseOutputService = output_service

    @property
    def name(self) -> str:
        """Name of the output."""
        return self._name

    @property
    def archived(self) -> bool:
        """Whether the output is archived or not."""
        return self._archived

    def get_mc_all_area(self, frequency: Frequency, data_type: MCAllAreasDataType, area: str) -> pd.DataFrame:
        """Get data for an area with mc-all.

        Args:
            frequency: Whether "hourly", "daily", "weekly", "monthly", "annual".
            data_type: The data-type of mc-all areas.
            area: The area name.

        Returns:
            A dataframe of mc-all data.
        """
        file_path = f"mc-all/areas/{area}/{data_type.value}-{frequency.value}"
        return self._output_service.get_matrix(self.name, file_path, frequency)

    def get_mc_all_link(
        self, frequency: Frequency, data_type: MCAllLinksDataType, area_from: str, area_to: str
    ) -> pd.DataFrame:
        """Get data for a link with mc-all.

        Args:
            frequency: Whether "hourly", "daily", "weekly", "monthly", "annual".
            data_type: The data-type of mc-all links.
            area_from: `area_from` ID.
            area_to: `area_to` ID.

        Returns:
            A dataframe of mc-all data.
        """
        if [area_from, area_to] != sorted([area_from, area_to]):
            raise OutputDataRetrievalError(self.name, "Areas should be sorted alphabetically")
        file_path = f"mc-all/links/{area_from} - {area_to}/{data_type.value}-{frequency.value}"
        return self._output_service.get_matrix(self.name, file_path, frequency)

    def get_mc_ind_area(
        self, mc_year: int, frequency: Frequency, data_type: MCIndAreasDataType, area: str
    ) -> pd.DataFrame:
        """Get data for an area with mc-ind.

        Args:
            mc_year: Monte-Carlo year index.
            frequency: Whether "hourly", "daily", "weekly", "monthly", "annual".
            data_type: The data-type of mc-all areas.
            area: The area name.

        Returns:
            A dataframe of mc-ind data.
        """
        file_path = f"mc-ind/{mc_year:05}/areas/{area}/{data_type.value}-{frequency.value}"
        return self._output_service.get_matrix(self.name, file_path, frequency)

    def get_mc_ind_link(
        self, mc_year: int, frequency: Frequency, data_type: MCIndLinksDataType, area_from: str, area_to: str
    ) -> pd.DataFrame:
        """Get data for a link with mc-ind.

        Args:
            mc_year: Monte-Carlo year index.
            frequency: "hourly", "daily", "weekly", "monthly", "annual".
            data_type: The data-type of mc-ind links.
            area_from: `area_from` ID.
            area_to: `area_to` ID.

        Returns:
            A dataframe of mc-ind data.
        """
        if [area_from, area_to] != sorted([area_from, area_to]):
            raise OutputDataRetrievalError(self.name, "Areas should be sorted alphabetically")
        file_path = f"mc-ind/{mc_year:05}/links/{area_from} - {area_to}/{data_type.value}-{frequency.value}"
        return self._output_service.get_matrix(self.name, file_path, frequency)

    def aggregate_mc_ind_areas(
        self,
        data_type: MCIndAreasDataType,
        frequency: Frequency,
        mc_years: Optional[list[int]] = None,
        areas_ids: Optional[list[str]] = None,
        columns_names: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        """Return a matrix of aggregated raw data for areas with mc-ind

        Args:
            data_type: values from McIndAreasDataType.
            frequency: values from Frequency.

        Returns:
            Aggregated raw data.
        """
        aggregation_entry = AggregationEntry(
            data_type=data_type,
            frequency=frequency,
            mc_years=mc_years,
            type_ids=areas_ids,
            columns_names=columns_names,
        )

        return self._output_service.aggregate_values(self.name, aggregation_entry, "areas", "ind")

    def aggregate_mc_ind_links(
        self,
        data_type: MCIndLinksDataType,
        frequency: Frequency,
        mc_years: Optional[list[int]] = None,
        links_ids: Optional[list[tuple[str, str]]] = None,
        columns_names: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        """Return a matrix of aggregated raw data for links with mc-ind

        Args:
            data_type: values from McIndLinks
            frequency: values from Frequency

        Returns:
            Aggregated raw data
        """
        type_ids = (
            [f"{area_from} - {area_to}" for link_id in links_ids for area_from, area_to in [sorted(link_id)]]
            if links_ids
            else None
        )

        aggregation_entry = AggregationEntry(
            data_type=data_type,
            frequency=frequency,
            mc_years=mc_years,
            type_ids=type_ids,
            columns_names=columns_names,
        )

        return self._output_service.aggregate_values(self.name, aggregation_entry, "links", "ind")

    def aggregate_mc_all_areas(
        self,
        data_type: MCAllAreasDataType,
        frequency: Frequency,
        areas_ids: Optional[list[str]] = None,
        columns_names: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        """Return a matrix of aggregated raw data for areas with mc-all

        Args:
            data_type: values from McAllAreas
            frequency: values from Frequency

        Returns:
            Aggregated raw data
        """
        aggregation_entry = AggregationEntry(
            data_type=data_type,
            frequency=frequency,
            type_ids=areas_ids,
            columns_names=columns_names,
        )

        return self._output_service.aggregate_values(self.name, aggregation_entry, "areas", "all")

    def aggregate_mc_all_links(
        self,
        data_type: MCAllLinksDataType,
        frequency: Frequency,
        links_ids: Optional[list[tuple[str, str]]] = None,
        columns_names: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        """Return a matrix of aggregated raw data for links with mc-all.

        Args:
            data_type: values from McAllLinks
            frequency: values from Frequency

        Returns:
            Aggregated raw data.
        """
        type_ids = (
            [f"{area_from} - {area_to}" for link_id in links_ids for area_from, area_to in [sorted(link_id)]]
            if links_ids
            else None
        )

        aggregation_entry = AggregationEntry(
            data_type=data_type,
            frequency=frequency,
            type_ids=type_ids,
            columns_names=columns_names,
        )

        return self._output_service.aggregate_values(self.name, aggregation_entry, "links", "all")

    def get_xpansion_result(self) -> XpansionResult:
        """Get xpansion result.

        Returns:
            Xpansion results.
        """
        return self._output_service.get_xpansion_result(self.name)

    def get_xpansion_sensitivity_result(self) -> XpansionSensitivityResult:
        """Get xpansion sensitivity results.

        Returns:
            Xpansion sensitivity results.
        """
        return self._output_service.get_xpansion_sensitivity_result(self.name)

    def get_solar_ts_numbers(self, area_id: str) -> dict[int, int]:
        """Get solar time series numbers.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_solar_ts_numbers(area_id, self._name)

    def get_wind_ts_numbers(self, area_id: str) -> dict[int, int]:
        """Get wind time series numbers for a given area.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_wind_ts_numbers(area_id, self._name)

    def get_load_ts_numbers(self, area_id: str) -> dict[int, int]:
        """Get load time series numbers for a given area.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_load_ts_numbers(area_id, self._name)

    def get_hydro_ts_numbers(self, area_id: str) -> dict[int, int]:
        """Get hydro time series numbers for a given area.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_hydro_ts_numbers(area_id, self._name)

    def get_binding_constraint_ts_numbers(self, group_id: str) -> dict[int, int]:
        """Get binding constraint time series numbers for a given constraint group.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_binding_constraint_ts_numbers(group_id, self._name)

    def get_thermal_ts_numbers(self, area_id: str, thermal_id: str) -> dict[int, int]:
        """Get thermal time series numbers for a given thermal cluster.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_thermal_ts_numbers(area_id, thermal_id, self._name)

    def get_st_storage_inflows_numbers(self, area_id: str, st_storage_id: str) -> dict[int, int]:
        """Get short-term storage inflows time series numbers for a given st-storage.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_st_storage_inflows_numbers(area_id, st_storage_id, self._name)

    def get_st_storage_additional_constraints_numbers(self, area_id: str, st_storage_id: str, constraint_id: str) -> dict[int, int]:
        """Get short-term storage additional constraints time series numbers for a given constraint.

        Returns:
            A mapping from the Monte-Carlo year to its selected time series
        """
        return self._output_service.get_st_storage_additional_constraints_numbers(area_id, st_storage_id, constraint_id, self._name)

# todo: add links