name: CI
on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 9
      matrix:
        os: [ windows-latest, ubuntu-22.04 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox~=4.25.0
          pip install tox-uv~=1.25.0

      - name: Performs Ubuntu tests
        if: matrix.os != 'windows-latest'
        run: |
          tox -e lint-ci
          tox -p

      - name: Performs Windows tests
        if: matrix.os == 'windows-latest'
        run: tox -e py3.10-test
