name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: 3.9
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check formatting
        run: ruff format --check src tests

      - name: Check typing
        run: |
          python -m mypy    

      - name: Run tests
        run: |
          pytest

      - name: Upload test results (only for Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/

#  sonarcloud:
#        runs-on: ${{ matrix.os }}
#        strategy:
#          matrix:
#            os: [ ubuntu-latest, macos-latest, windows-latest ]
#        needs: [ci]
#        steps:
#          - uses: actions/checkout@v4
#          - name: Download python coverage report
#            uses: actions/download-artifact@v4
#            with:
#              name: python-code-coverage-report
#          - name: SonarCloud Scan
#            uses: sonarsource/sonarcloud-github-action@v2.3.0
#            env:
#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
